Migrate project from sbt to Mill build tool, update workflows and makefile accordingly.

diff --git a/.github/workflows/scala.yml b/.github/workflows/scala.yml
--- a/.github/workflows/scala.yml
+++ b/.github/workflows/scala.yml
@@ -13,10 +13,13 @@ jobs:
         with:
           distribution: temurin
           java-version: 21
-      - name: Setup sbt launcher
-        uses: sbt/setup-sbt@v1
       - name: Build and Test
+        run: ./mill _.test
         env:
           PHOTOS_ELASTIC_ENABLED: false
           PHOTOS_FILE_SYSTEM_SEARCH_LOCK_DIRECTORY: ""
-        run: sbt test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
